name: midterm_userpage
description: "A new Flutter project."
publish_to: 'Aldous Omictin'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "lib/assets/icons/ios/AppIcon-29@3x.png"
  image_path_android: "lib/assets/icons/android/res/mipmap-xxxhdpi/ic_launcher.png"
  remove_alpha_ios: true
  min_sdk_android: 16 
  adaptive_icon_foreground: "lib/assets/icons/android/res/mipmap-xxhdpi/ic_launcher_foreground.png"
  adaptive_icon_background: "lib/assets/icons/android/res/mipmap-xxhdpi/ic_launcher_background.png"
  adaptive_icon_inset: 16
  adaptive_icon_monochrome: "lib/assets/icons/android/res/mipmap-xxhdpi/ic_launcher_monochrome.png"
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "lib/assets/icons/web/icon-512.png"
  windows:
    generate: true
    image_path: "lib/assets/icons/web/icon-512.png"
    icon_size: 48